### PR TITLE
Fix: Validator fixed for STAC based layer using joi 

### PR DESCRIPTION
**Pull request by srijitcoder**
## Implemented changes
- Fixed STAC based validator using Joi 

### Issue - 
image

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [x] All checks have passed
- [x] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [x] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

### CODE REVIEW

**Review by lubojr — CHANGES_REQUESTED** [review]
If I am not mistaken, then eoxmap layer of type 'stac' is directly mapped to ol-stac STACLayer https://m-mohr.github.io/ol-stac/en/latest/apidoc/module-ol_layer_STAC-STACLayer.html therefore the schema should be corresponding to this class and its properties.

For example following config now does not pass validation
```
## <!--{as="eox-map" id="palsar" mode="tour" layers='[{"type":"STAC","url":"https://eurodatacube.github.io/eodash-catalog/trilateral/FNF_Palsar/FNF_Palsar/FNF_Palsar/2020/2020.json","displayWebMapLink":true,"displayFootprint":false}]'}-->
```

**Comment by srijitcoder** [comment]
> If I am not mistaken, then eoxmap layer of type 'stac' is directly mapped to ol-stac STACLayer https://m-mohr.github.io/ol-stac/en/latest/apidoc/module-ol_layer_STAC-STACLayer.html therefore the schema should be corresponding to this class and its properties.
> 
> 
> 
> For example following config now does not pass validation
> 
> ```
> 
> ## 
> 
> ```
> 
> image
> 
> 

If I am correct there must be an ’id’ required on each layer in ’eox-map’ and ’id’ is mentioned inside a ’properties’ that’s why that error is popped otherwise the ’source’ related error won't appear.

**Review by lubojr — APPROVED** [review]

**Comment by lubojr** [comment]
Thank you for clarification. Sorry, oversight on my side, I forgot that `properties.id` is required.

**Review by lubojr — CHANGES_REQUESTED** [review]
The additional props passed to STACLayer are marked as "not allowed": 

```
## <!--{ as="eox-map" id="tipping-points-map" mode="tour" layers='[{"type":"STAC","url":"https://eurodatacube.github.io/eodash-catalog/trilateral/ndvi/ndvi/ndvi/2023/2023-06-15T23:59:30Z.json","displayWebMapLink":true,"displayFootprint":false,"properties":{"id":"ndvi_layer"}}]' }-->
```

**Comment by srijitcoder** [comment]
> The additional props passed to STACLayer are marked as "not allowed":

Any pattern of key will be allowed inside the layer's object schema.

**Review by lubojr — APPROVED** [review]

**Review by silvester-pari — APPROVED** [review]
Thank you both for refining this fix. Looks good to merge now!

**Pull request merged**
