### PR TITLE
Feat: Auto save in StoryTelling

### PR DESCRIPTION
**Pull request by srijitcoder**
## Implemented changes
- Auto saving added (Triggers every 2.5 seconds after editing editor)
- Stored inside `localstorage`
- Confirm prompt to load previous markdown again or not
- Works only when `editor` is enabled

## Screenshots/Videos

https://github.com/EOX-A/EOxElements/assets/10809211/0cedaf54-006d-455c-b669-d6096476c048

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [x] All checks have passed
- [x] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [x] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

### CODE REVIEW

**Review by silvester-pari — COMMENTED** [review]
Looks nice! Is there a way to clear the storage? I think now when you refresh the page and don't want to recover from last time, it keeps asking each time you load the page.

**Review by lubojr — APPROVED** [review]
Looks great! Thank you!

**Comment by srijitcoder** [comment]
> Looks nice! Is there a way to clear the storage? I think now when you refresh the page and don't want to recover from last time, it keeps asking each time you load the page.

Umm, I tried to look at the pattern of https://geojson.io/ and it also prompts each time we refresh the page. 
I mean do you have any suggestions on how we can break the loop? 
One way is to check whether the markdown in local storage is similar to the markdown we are passing or not.

**Review by santilland — APPROVED** [review]
As described in comment, in principle ok to merge

**Pull request merged**
