### PR TITLE
feat: lonLatCenter & lonLatExtent

### PR DESCRIPTION
**Pull request by RobertOrthofer**
## Implemented changes

This PR adds the read-only-properties `EOxMap.lonLatCenter` and `EOxMap.lonLatExtent`, which return the current center and extent in EPSG:4326, no matter the current projection of the view. 
Additionally, the new methods `transform` and `transformExtent` are now exposed, allowing more flexible transformations between all registered coordinate systems. Basically, these methods are the `ol/proj` [transform](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transform) and [transformExtent](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transformExtent) functions, with the small adaptation that the `destination` defaults to `EPSG:4326` if not defined.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added a test related to this feature/fix
- [x] For new features: I have created a story showcasing this new feature
- [x] All checks have passed
- [x] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [x] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

### CODE REVIEW

**Review by silvester-pari — CHANGES_REQUESTED** [review]
Again, here it would be nice to have a story showcasing this.

Plus, some description/documentation for the API docs: 
image

**Comment by silvester-pari** [comment]
I added a **very** basic story showcasing this, but probably better than nothing.

**Review by silvester-pari — APPROVED** [review]

**Comment by RobertOrthofer** [comment]
Thanks for the story. We should do documentation of all utility functions in the same place, once they are all exported. They probably don't need a map in their story

**Review by santilland — APPROVED** [review]
Initial integration tests showed a small issue that was corrected, further tests seem to work as expected, so i think this is good to go!
Thank you @RobertOrthofer for the implementation!

**Pull request merged**
