### PR TITLE
fix: check for tooltip element in shadowroot

### LINKED ISSUE #549: Setting layers multiple times destroys tooltip functionality
I'm setting `layers` prop with interactions multiple times, after each relevant user interaction. Tooltip is defined with `eox-map-tooltip` element. The first time the tooltip shows, but subsequently, no tooltip is shown and the tooltip has even vanished from the DOM.

Possibly, this line does not work when setting interactions multiple times:

https://github.com/EOX-A/EOxElements/blob/00d7af5efa6bce88912c701e8dd777b9f8c794ec/elements/map/src/select.ts#L53

I've tried with, but I was not successful so far. My insight is limited, however.

```js
    this.tooltip =
      this.eoxMap.querySelector("eox-map-tooltip") ||
      this.eoxMap.shadowRoot.querySelector("eox-map-tooltip") ||
      options.overlay?.element;
```

### PR DESCRIPTION
**Pull request by silvester-pari**
This PR adds an additional check to find the tooltip element inside the map shadow root and fixes #549. The reason for this is that OpenLayers "hijacks" the DOM element and pulls it into its DOM, changing the location from the slot (outside the shadow root) into its own div (inside the shadow root).
This fix does not consider the overlay element option, as this is tracked in a separate issue (#548).

### CODE REVIEW

**Comment by StefanBrand** [comment]
This PR does not fix the issue. I can still reproduce it in the application.

**Comment by StefanBrand** [comment]
Tooltips work for multiple layers now. However, we also get tooltips for `singleclick` interactions:

[Peek 2024-01-12 10-50.webm](https://github.com/EOX-A/EOxElements/assets/8948865/3614c304-4eb0-4de4-bfe1-2290d58a48d5)

**Comment by StefanBrand** [comment]
Workaround is to remove the unnecessary overlays on `loadend`:

```
      olMap
        .getOverlays()
        .getArray()
        .filter((overlay) => overlay.options.element.id.includes(CLICK_INTERACTION_SUFFIX))
        .forEach((overlay) => olMap.removeOverlay(overlay));
```

However the property transform seems to be broken. :grimacing:

**Comment by silvester-pari** [comment]
Superseded by https://github.com/EOX-A/EOxElements/pull/571.

**Pull request closed without merging**
